development: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: boilerplate_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
test:
  <<: *defaults
  database: boilerplate_development_test
production:
  <<: *defaults
  database: boilerplate_development_prod
